### ISSUE TITLE
Problem with account to login metabase

### ISSUE THREAD

**Issue by harrydevforlife** [dominikhei/Local-Data-LakeHouse#1]
Hi dominikhei,

Thank you for the useful repository, I have try your code to make lakehouse at local. Everythings is ok, but the account to login Metabase that you leave in the readme.md, `test` and `test123!`, it is not work. The Metabase login page require a email, so your account not work in there. Please help me fix this case. Thank you so much !!
![Uploading Screenshot 2023-05-14 233126.png…]()

**Comment by Metrea** [comment]
same issue on my end

**Comment by dominikhei** [comment]
Hello, sorry for not getting back to you so far. I have changed the readme and added the mail for the login, please try it out now and reach back to me, so that I can close this issue. 
Thanks
